- name: Check if Xcode is installed.
  ansible.builtin.stat:
    path: /Applications/Xcode.app
  register: xcode_app
  tags:
    - xcode

- name: Check if Xcode license has been accepted.
  ansible.builtin.shell: /usr/bin/xcrun clang 2>&1 | grep -q "license"
  register: xcode_license_check
  changed_when: false
  failed_when: false
  when: xcode_app.stat.exists
  tags:
    - xcode

- name: Accept Xcode license agreement.
  ansible.builtin.command: sudo xcodebuild -license accept
  become: true
  when:
    - xcode_app.stat.exists
    - xcode_license_check.rc == 0
  tags:
    - xcode