format = """\
[](bg:#16191d fg:#8cc265)\
[ ](bg:#8cc265 fg:#16191d)\
[](bg:#e05561 fg:#8cc265)\
$username\
[](bg:#4aa5f0 fg:#e05561)\
$directory\
${custom.directory_end_with_git}\
${custom.directory_end_without_git}\
$git_branch\
$git_status\
$git_metrics\
${custom.git_end}\
$python\
$nodejs\
$line_break\
$character\
"""

command_timeout = 1000

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold fg:#ea9936'
symbol = " "

[custom.directory_end_with_git]
when = 'git rev-parse --is-inside-work-tree'
format = '[]($style)'
style = 'bg:#D4D8DF fg:#4aa5f0'

[custom.directory_end_without_git]
when = '[[ "$(git rev-parse --is-inside-work-tree)" != "true" ]]'
format = '[]($style)'
style = 'bg:#16191d fg:#4aa5f0'

[custom.git_end]
when = 'git rev-parse --is-inside-work-tree'
format = '[ ](bg:#D4D8DF)[]($style)'
style = 'bg:#16191d fg:#D4D8DF'

[username]
format = '[ $user ]($style)'
style_user = 'bg:#e05561 fg:#16191d'
style_root = 'bg:#e05561 fg:#16191d'
disabled = false
show_always = true

[directory]
format = '[  $path ]($style)'
style = 'bg:#4aa5f0 fg:#16191d'

[git_branch]
symbol = '  '
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = 'bg:#D4D8DF fg:#16191d'

[git_status]
format = '[$all_status]($style)'
style = 'bold bg:#D4D8DF fg:#16191d'

[git_metrics]
format = '([+$added]($added_style))[]($added_style)'
added_style = 'bold bg:#D4D8DF fg:#16191d'
deleted_style = 'bold bg:#D4D8DF fg:#16191d'
disabled = false

[hg_branch]
format = '[ $symbol$branch ]($style)'
symbol = ' '

[character]
success_symbol = '[ ┗━󰆢](bold fg:#8cc265)'
error_symbol = '[✗](fg:#e05561)'

[python]
symbol = ' '
format = ' via [${symbol}](fg:#316EA7)[(${version} )(\($virtualenv\) )]($style)'
style = 'bold fg:#FFD340'
pyenv_prefix = 'venv'
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
detect_extensions = ['py']
version_format = 'v${raw}'

[nodejs]
format = ' via [ $version](bold bg:#16191d fg:#5BAF3F)'
detect_files = ['package.json']
detect_folders = ['node_modules']
