- name: Check if SSH configuration file exists.
  ansible.builtin.file:
    path: $HOME/.ssh
    state: directory
  tags:
    - ssh

- name: Generate GitHub SSH key.
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: "$HOME/.ssh/id_ed25519_github"
    ssh_key_passphrase: "{{ github.ssh_key_passphrase }}"
    ssh_key_comment: "{{ github.email_address }}"
    force: no
  no_log: True
  register: user_ssh_key_status
  tags:
    - ssh

- name: Copy SSH configuration file to user's SSH directory.
  ansible.builtin.copy:
    src: ../templates/config
    dest: $HOME/.ssh/config
  tags:
    - ssh

- name: Add the SSH private key to the ssh-agent.
  ansible.builtin.shell: expect -c 'spawn ssh-add --apple-use-keychain {{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github; expect "Enter passphrase for {{ lookup('env', 'HOME') }}/.ssh/id_ed25519_github:"; send "{{ github.ssh_key_passphrase }}\n"; expect eof'
  when: user_ssh_key_status.changed
  no_log: True
  tags:
    - ssh